import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/constants/app_colors.dart';
import '../../core/utils/app_error_handler.dart';
import '../../providers/auth_provider.dart';
import '../../providers/locale_provider.dart';
import '../../models/report_model.dart';
import '../../models/user_model.dart';
import '../../services/firestore_service.dart';

import '../../widgets/buttons/primary_button.dart';
import '../../widgets/inputs/custom_text_field.dart';

class ReportDialog extends StatefulWidget {
  final UserModel reportedUser;


  const ReportDialog({super.key, required this.reportedUser});

  @override
  State<ReportDialog> createState() => _ReportDialogState();
}

class _ReportDialogState extends State<ReportDialog> {
  final _reasonController = TextEditingController();
  final _formKey = GlobalKey<FormState>();
  bool _isLoading = false;

  @override
  void dispose() {
    _reasonController.dispose();
    super.dispose();
  }

  Future<void> _submitReport() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    final currentUser = context.read<AuthProvider>().user!;
    final navigator = Navigator.of(context);
    final messenger = ScaffoldMessenger.of(context);
    final locale = context.read<LocaleProvider>().locale.languageCode;

    try {
      final report = ReportModel(
        id: '', // Generated by Firestore
        reporterId: currentUser.id,
        reporterName: currentUser.name,
        reportedUserId: widget.reportedUser.id,
        reportedUserName: widget.reportedUser.name,
        reportedUserPhone: widget.reportedUser.phoneNumber,
        reason: _reasonController.text.trim(),
        createdAt: DateTime.now(),
      );

      await FirestoreService().submitReport(report);

      if (mounted) {
        navigator.pop();
        messenger.showSnackBar(
          SnackBar(
            content: Text(
              locale == 'ar' 
                  ? 'تم إرسال البلاغ بنجاح وسقوم الإدارة بمراجعته' 
                  : 'Report submitted successfully and will be reviewed',
            ),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e, stack) {
      if (mounted) {
        await AppErrorHandler.show(
          context,
          e,
          stack,
          logContext: 'ReportDialog._submitReport',
          customMessage: locale == 'ar'
              ? 'فشل إرسال البلاغ. يرجى المحاولة مرة أخرى.'
              : 'Failed to submit report. Please try again.',
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final locale = context.watch<LocaleProvider>().locale.languageCode;
    final isAr = locale == 'ar';

    return AlertDialog(
      title: Row(
        children: [
          Icon(Icons.report_problem, color: AppColors.error),
          const SizedBox(width: 8),
          Text(isAr ? 'إبلاغ عن مستخدم' : 'Report User'),
        ],
      ),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                isAr 
                    ? 'أنت على وشك الإبلاغ عن "${widget.reportedUser.name}". يرجى ذكر السبب بوضوح.'
                    : 'You are reporting "${widget.reportedUser.name}". Please state the reason clearly.',
                style: Theme.of(context).textTheme.bodyMedium,
              ),
              const SizedBox(height: 16),
              CustomTextField(
                label: isAr ? 'سبب البلاغ' : 'Reason',
                hint: isAr ? 'اشرح المشكلة بالتفصيل...' : 'Explain the issue in detail...',
                controller: _reasonController,
                maxLines: 4,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return isAr ? 'هذا الحقل مطلوب' : 'This field is required';
                  }
                  if (value.length < 10) {
                    return isAr ? 'يرجى كتابة تفاصيل أكثر' : 'Please provide more details';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 8),
              if (widget.reportedUser.phoneNumber != null)
                 Text(
                   isAr 
                       ? 'سيتم إرفاق رقم هاتف المستخدم تلقائياً مع البلاغ.'
                       : 'User phone number will be automatically attached.',
                   style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                 ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: Text(isAr ? 'إلغاء' : 'Cancel'),
        ),
        SizedBox(
          width: 100,
          child: GradientButton(
            text: isAr ? 'إرسال' : 'Submit',
            onPressed: _submitReport,
            isLoading: _isLoading,
            gradientColors: [AppColors.error, AppColors.error.withValues(alpha: 0.8)],
          ),
        ),
      ],
    );
  }
}
